# Generated by Django 5.0.6 on 2024-06-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeteorologicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('gti', models.FloatField()),
                ('ghi', models.FloatField()),
                ('dni', models.FloatField()),
                ('dhi', models.FloatField()),
                ('air_temp', models.FloatField()),
                ('rh', models.FloatField()),
                ('pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_dir', models.FloatField()),
                ('wind_gust', models.FloatField()),
                ('rain', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PVSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.FloatField()),
                ('inverter_type', models.CharField(max_length=100)),
                ('number_of_panels', models.IntegerField()),
                ('technology', models.CharField(max_length=100)),
                ('year_of_installation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('adresse', models.IntegerField()),
                ('i1', models.FloatField()),
                ('u_dc', models.FloatField()),
                ('p_dc', models.FloatField()),
                ('t1', models.FloatField()),
                ('t2', models.FloatField()),
                ('i_sum', models.FloatField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.pvsystem')),
            ],
        ),
    ]
