# Generated by Django 5.0.6 on 2024-06-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricaldata',
            name='adresse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='i1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='i_sum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='p_dc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='t1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='t2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricaldata',
            name='u_dc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='air_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='dhi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='dni',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='ghi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='gti',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='rain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='rh',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='wind_dir',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='wind_gust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meteorologicaldata',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
